### ISSUE TITLE
code=value doesn't update when value changes

### ISSUE THREAD

**Issue by sudowoodo200** [bouzidanas/streamlit-code-editor#1]
I have code that looks something like this
```
input = st.text_input("Enter")
code_editor(input, lang="python")
```

Even though input changes, the code_editor display doesn't.

**Comment by bouzidanas** [comment]
Hi, I think there might be a greater issue because the following worked for me:
`
import streamlit as st
import code_editor

input = st.text_input("Enter")
code_editor.code_editor(input, lang="python")
`
Changes are shown in the code editor

**Comment by sudowoodo200** [comment]
Yea you are right. Sorry -- it's cause there is interference from another component in my app. Thank you for quickly chasing this down

**Comment by bouzidanas** [comment]
No worries! 

FYI, I just recently added the ability to change input code for when the code_editor function is given a static key. This, as well as other performance improvements are in the latest version (release v0.9.0-alpha). You just have to set `allow_reset = True`. So for example,
```
import streamlit as st
import code_editor

input = st.text_input("Enter")
code_editor.code_editor(input, lang="python", allow_reset=True, key="code")
```
Because of the key, this will give you a code editor that isnt recreated from scratch everytime the streamlit script is rerun which makes it more stable in appearance (no flash of disappearance and reappearance). 

Im sharing this because the changes arent reflected in the docs yet.
