### ISSUE TITLE
Response_dict doesn't return anything

### ISSUE THREAD

**Issue by frankvgompel** [bouzidanas/streamlit-code-editor#4]
Although the editor seems to work, it eluded me how to capture the edited text since response_dict['text'] is empty.

```
import streamlit as st
from code_editor import code_editor

st.header("test")

exp = f"This is a test\nWith two lines"

response_dict = code_editor(code=exp)
result = response_dict.items()

st.write(response_dict)
```
<img width="503" alt="st_code_editor" src="https://github.com/bouzidanas/streamlit-code-editor/assets/81262671/a5c72325-d608-4007-b313-ef04b49c99f3">

**Comment by bouzidanas** [comment]
Without any buttons or key commands added, it will work much like [st.text_area](https://docs.streamlit.io/library/api-reference/widgets/st.text_area). The component will not send anything back until the user commands it to (via key commands or buttons). By default, I believe the code editor will return the contents to your python script when you press `[Ctrl-Enter]` exactly like Streamlit's text area component.

As to why this is, I believe I implemented a debounced response option, but it was janky because Streamlit HAS to rerender the python script EVERY time a response is sent back by the code editor and if your script is sensitive to rerenders in some way, the experience can be terrible.

**Comment by bouzidanas** [comment]
Oh also, quick tip if you just started exploring using the code editor. You will get nicer experience if you set `allow_reset=True` and give it a fixed key (like say `key="my_editor"`). This will prevent the editor from being recreated everytime your script reruns and also allowing you to change/update the arguments to the component.
